name: "VPS Deploy"
on:
  push:
    branches:
      - prod
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Build with Maven"
        run: mvn clean install -DskipTests

      - name: "Copy JAR to server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "target/quack-0.0.1-SNAPSHOT.jar"
          target: "/root/quack/"
        if: success() && steps.Check_for_changes_in_JAR_file.outputs.exit_code != 0

      # Rodar o JAR no servidor
      - name: "Run JAR on server"
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST}}
          username: ${{ secrets.REMOTE_USER}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: ${{ secrets.REMOTE_PORT}}
          script: |
            nohup java -jar /root/quack/quack-0.0.1-SNAPSHOT.jar --no-dev --no-progress - a > /root/quack/quack.log 2>&1 &
        if: success() && steps.Check_for_changes_in_JAR_file.outputs.exit_code != 0
